movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img= models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render (request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
    {% block body %}
<div class="login">
    <form method="post"  id="form" enctype="multipart/form-data">
        <h2>Add Form</h2>
        {% csrf_token %}
        
        <div class="input">
            <label for="name">Movie Name </label><br>
            <input id="t1" class="tb" type="text" name="name" placeholder="Enter your Movie Name"><br><br>
        </div>
        <div class="input">
            <label for="desc">Description </label><br>
            <input id="t1" class="tb" type="text" name="desc" placeholder="Enter the Movie Description"><br><br>
        </div>
        <div class="input">
            <label for="year">Year </label><br>
            <input id="t1" class="tb" type="text" name="year" placeholder="Enter your Movie year"><br><br>
        </div>
        <div class="input">
            <label for="password">Movie Image </label>
            <input id="t1" class="tb" type="file" name="img"><br>
        </div>
        <br><br>
        <button type="reset" class="btn">Reset</button>
        <button type="submit" class="btn">Submit</button>
    </form>
</div>  
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>index page</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}"
    </head>
    <body>
        <!-- Image and text -->
        <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
        <!-- <img src="" alt=""> -->
        Online Movie Store
        </a>
    </nav>
    {% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
    {% block body %}
<div class="login">
    <form method="post"  id="form" enctype="multipart/form-data">
        <h2>Delete Form</h2>
        {% csrf_token %}
        Are you sure to delete this Movie?
        <button type="submit" class="btn">Submit</button>
    </form>
</div>  
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container index">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
    <div class="col-md-6">
        <h4><b>Movie Name : </b></h4>{{movie.name}}
        <h4><b>Movie Description : </b></h4>{{movie.desc}}
        <h4><b>Movie Year : </b></h4>{{movie.year}}<br><br>
        <a class="btn btn-success" href="{% url 'movieapp:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>
   </div>
</div>
{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

templates/index.html
    {% extends 'base.html' %}
    {% block body %}

    <div class="container-lg index" >
        <div class="row">
            {% for i in movie_list %}
            <div class="col-md-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.img.url}}" class="card-img-top" width="150px" height="250px">
                    <div class="card-body">
                      <h5 class="card-title">{{i.name}}</h5>
                      <p class="card-text">{{i.desc}}</p>
                      <p class="card-text">{{i.year}}</p>
                      <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go --></a>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}